version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  maildev_container:
    image: maildev/maildev
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  mongodb_data_container: